FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    file \
    fuse \
    git \
    libdbus-1-3 \
    libfontconfig1 \
    libfuse2 \
    libgl1-mesa-glx \
    libglu1-mesa-dev \
    libpulse-mainloop-glib0 \
    libssl-dev \
    libxcb1 \
    libxrender1 \
    mesa-common-dev \
    python3 \
    python3-pip \
    python3-setuptools \
    qttools5-dev-tools \
    unzip \
    wget \
    && apt-get clean

# Install more recent CMAKE
RUN wget https://github.com/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-linux-x86_64.sh -O /tmp/cmake.sh \
    && chmod +x /tmp/cmake.sh \
    && /tmp/cmake.sh --skip-license --prefix=/usr/local \
    && rm /tmp/cmake.sh

RUN ln -s /usr/bin/python3 /usr/bin/python && \
    pip3 install -U pip && \
    pip3 install jinja2 aqtinstall==v2.2.3

COPY tools/aqt-settings.ini .

# Install QT
ENV QT=5.15.2
ENV QT_ARCH=gcc_64
ENV AQT_CONFIG=aqt-settings.ini
RUN aqt install-qt --outputdir /opt/qt linux desktop ${QT} ${QT_ARCH} -m all

ENV CMAKE_PREFIX_PATH="/opt/qt/${QT}/${QT_ARCH}"
ENV PATH="/opt/qt/${QT}/${QT_ARCH}/bin:$PATH"
ENV QT_PLUGIN_PATH="/opt/qt/${QT}/${QT_ARCH}/plugins/"
ENV QML_IMPORT_PATH="/opt/qt/${QT}/${QT_ARCH}/qml/"
ENV QML2_IMPORT_PATH="/opt/qt/${QT}/${QT_ARCH}/qml/"

# Download linuxdeploy tools
RUN wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage -O /tmp/linuxdeploy.AppImage && \
    chmod +x /tmp/linuxdeploy.AppImage
RUN wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage -O /tmp/linuxdeploy-plugin-qt.AppImage && \
    chmod +x /tmp/linuxdeploy-plugin-qt.AppImage

# Enable auto extract+run for AppImages, so no FUSE is required
ENV APPIMAGE_EXTRACT_AND_RUN=1

WORKDIR /ping-viewer
COPY . .

CMD ["bash", "-c", "tools/compile.sh"]
